sudo: required

services:
  - docker

language: python

install:
  - docker --version

script:
  - true

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master