version: 2
jobs:
  deploy:
    working_directory: ~/mosquitto-with-http-auth
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t mosquitto-with-http-auth .
            docker tag mosquitto-with-http-auth:latest datacake/mosquitto-with-http-auth:$(git describe --always)
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push datacake/mosquitto-with-http-auth:$(git describe --always)
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master